### ISSUE TITLE
Serious BUG in IE

### ISSUE THREAD

**Issue by barat** [leonardfischer/Kohana-Google-Maps-Module#1]
In the View You have serious bug.
In Internet Explorer last element of javascript array can't have comma or You will get error:
<b>"Expected identifier, string or number"</b>

Example article (found in google)
http://forumsblogswikis.com/2008/07/21/javascript-error-expected-identifier-string-or-number-in-ie/

It's not just IE6, but 7 and 8 as well, so You realy have to make tests on IE.

**Comment by leonardfischer** [comment]
Hi Barat,
thanks for reporting!

I believe a solution may be changing JSON keys from:
var test = {key_1: 'value_1', key_2: 'value_2'};

to:
var test = {'key_1': 'value_1', 'key_2': 'value_2'};

I'll check, when I'm home and push a solution.

Thanks again!

**Comment by barat** [comment]
It's not json but your default view. There You make whole <script> thing, but You leave last comma in each array/params ;)

For example here:

https://github.com/solidsnake/Kohana-Google-Maps-Module/blob/master/views/gmap.php#L36-43

You will get last "," in array + Error in IE ;)

**Comment by leonardfischer** [comment]
Alright, I pushed a bugfix - I tested it in IE 7 and 8. I hope it works for you aswell :)

**Comment by barat** [comment]
I fixed it by my own, no json - just changed if/else places to not include comma if not needed ;)
But Your solluton may be cleaner ;)

Thnking about geocode function? For example getting lat/lng from given address? ;)

BTW. Polygon and Polylines can make same bug because of comas ;)

**Comment by leonardfischer** [comment]
Mh, I thought about it - yes... But I'm not sure if that stuff belongs in this module. Also I believe there's already another module for that.

If you're looking for some great Kohana modules, take a look at https://github.com/ahutchings/kohana-modules

**Comment by barat** [comment]
Yes I used and Fixed one plugin for geocode (deprecated functions, some bad checking etc) and placed it inside Your  module ;)
But this is just a sugestion ;)

**Comment by leonardfischer** [comment]
Well, if it's fully integrated you could send me a pull request :D

**Comment by barat** [comment]
Can't - old module. I found this one - pretier, cleaner ... and I think that only thng it have to be done is changing name to geocode and maybe remove "key" part, because v3 doesn't need keys ;)
https://github.com/guillermin/gmaps
