### ISSUE TITLE
validation of lat and lng

### ISSUE THREAD

**Issue by bumperbox** [leonardfischer/Kohana-Google-Maps-Module#3]
i think you have you validation of latitude and longitude back to front. 
the test for +/- 90 should be swapped with the test for +/- 180

function validate_latitude
function validate_longitude

(i could be wrong i am no cartographer)

try the co-ordinates for new zealand for example

```
        'lat' => -38.687542,
        'lng' => 176.070282
```

**Comment by leonardfischer** [comment]
Mh, I'll have to check that when I'm home. But it seems you're right!
